//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace memory_game.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("memory_game.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static System.Drawing.Bitmap blocks1
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks10
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks100
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks101
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks102
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks102", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks103
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks103", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks104
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks104", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks105
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks105", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks106
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks106", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks107
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks107", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks108
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks108", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks109
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks109", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks11
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks110
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks110", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks111
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks112
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks112", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks113
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks113", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks114
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks114", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks115
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks115", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks116
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks116", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks117
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks117", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks118
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks118", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks119
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks119", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks12
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks120
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks121
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks122
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks122", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks123
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks123", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks124
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks124", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks125
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks125", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks126
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks126", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks127
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks127", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks128
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks129
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks13
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks130
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks130", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks131
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks131", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks132
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks132", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks133
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks133", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks134
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks134", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks135
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks135", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks136
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks136", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks137
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks137", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks138
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks138", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks139
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks139", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks14
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks140
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks140", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks141
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks141", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks142
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks142", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks143
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks143", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks144
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks145
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks145", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks15
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks16
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks17
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks18
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks19
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks2
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks20
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks21
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks22
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks23
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks24
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks25
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks26
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks27
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks28
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks29
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks3
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks30
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks31
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks32
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks33
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks34
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks35
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks35", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks36
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks37
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks38
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks38", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks39
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks4
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks40
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks41
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks42
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks43
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks43", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks44
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks45
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks46
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks46", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks47
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks47", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks48
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks49
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks49", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks5
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks50
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks51
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks52
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks52", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks53
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks53", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks54
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks54", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks55
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks55", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks56
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks56", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks57
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks57", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks58
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks58", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks59
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks59", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks6
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks60
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks60", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks61
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks62
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks62", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks63
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks63", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks64
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks65
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks65", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks66
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks66", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks67
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks67", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks68
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks68", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks7
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks70
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks70", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks71
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks72
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks73
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks73", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks74
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks74", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks75
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks75", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks76
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks76", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks77
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks77", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks78
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks78", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks79
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks79", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks8
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks81
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks81", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks82
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks82", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks83
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks83", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks84
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks84", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks85
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks85", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks86
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks86", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks87
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks87", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks88
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks89
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks89", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks9
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks90
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks91
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks91", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks92
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks92", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks93
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks93", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks94
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks94", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks95
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks95", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks96
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks97
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks97", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks98
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks98", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap blocks99
        {
            get
            {
                object obj = ResourceManager.GetObject("blocks99", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap question
        {
            get
            {
                object obj = ResourceManager.GetObject("question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap smiley_fail
        {
            get
            {
                object obj = ResourceManager.GetObject("smiley_fail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap smiley_match
        {
            get
            {
                object obj = ResourceManager.GetObject("smiley_match", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap smiley_smile
        {
            get
            {
                object obj = ResourceManager.GetObject("smiley_smile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap smiley_win
        {
            get
            {
                object obj = ResourceManager.GetObject("smiley_win", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.IO.UnmanagedMemoryStream sound_fail
        {
            get
            {
                return ResourceManager.GetStream("sound_fail", resourceCulture);
            }
        }

        public static System.IO.UnmanagedMemoryStream sound_match
        {
            get
            {
                return ResourceManager.GetStream("sound_match", resourceCulture);
            }
        }

        public static System.Drawing.Bitmap sound_off
        {
            get
            {
                object obj = ResourceManager.GetObject("sound_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap sound_on
        {
            get
            {
                object obj = ResourceManager.GetObject("sound_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.IO.UnmanagedMemoryStream sound_win
        {
            get
            {
                return ResourceManager.GetStream("sound_win", resourceCulture);
            }
        }
    }
}
